### ISSUE TITLE
Make API more like Apollos

### ISSUE THREAD

**Issue by brysgo** [brysgo/graphql-gun#3]
Throwing this comment from @stubailo here since I would like to do this.

> I think an API more like Apollo's will make more sense since this container actually has an entire, GraphQL query, not just a fragment! http://dev.apollodata.com/react/queries.html#basics
> 
> In this case, would be:
> 
> const ColorContainer = graphql(gql`{ ... }`, {name: 'palette'})(Color)
> An additional benefit is that the above API can be used with stuff like recompose because it takes arguments in the same way as other HoCs.

**Comment by brysgo** [comment]
@stubailo - could you tell me if that is what you had in mind?

**Comment by stubailo** [comment]
Yeah looks great!

**Comment by brysgo** [comment]
Thanks, I'm going to document it and then close this :-)
